// Package container provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package container

import (
	"encoding/json"
	"fmt"

	externalRef0 "github.com/dcm-project/catalog-manager/api/v1alpha1/servicetypes"
)

// ContainerPort Container port specification
type ContainerPort struct {
	// ContainerPort Port number inside container
	ContainerPort        int                    `json:"containerPort"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerResources Resource allocation (CPU and memory)
type ContainerResources struct {
	// Cpu CPU allocation (in cores)
	Cpu CpuResources `json:"cpu"`

	// Memory Memory allocation
	Memory               MemoryResources        `json:"memory"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContainerSpec defines model for ContainerSpec.
type ContainerSpec struct {
	// Image Container image specification.
	// Based on OCI Image Specification for portable image references.
	Image Image `json:"image"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Network Network and port configuration (optional)
	Network *Network `json:"network,omitempty"`

	// Process Container process configuration (optional)
	Process *Process `json:"process,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"providerHints,omitempty"`

	// Resources Resource allocation (CPU and memory)
	Resources ContainerResources `json:"resources"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType          externalRef0.ServiceType `json:"serviceType"`
	AdditionalProperties map[string]interface{}   `json:"-"`
}

// CpuResources CPU allocation (in cores)
type CpuResources struct {
	// Max Maximum allowed CPU cores
	Max int `json:"max"`

	// Min Minimum guaranteed CPU cores
	Min                  int                    `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// EnvVar Environment variable definition
type EnvVar struct {
	// Name Variable name
	Name string `json:"name"`

	// Value Variable value
	Value                string                 `json:"value"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Image Container image specification.
// Based on OCI Image Specification for portable image references.
type Image struct {
	// Reference Complete OCI image reference.
	//
	// Format: [REGISTRY/]REPOSITORY[:TAG|@DIGEST]
	// Examples:
	// - quay.io/organization/app:v1.2.3 (registry + tag)
	// - docker.io/library/nginx:latest (Docker Hub)
	// - gcr.io/project/image@sha256:abc123... (digest)
	Reference            string                 `json:"reference"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MemoryResources Memory allocation
type MemoryResources struct {
	// Max Maximum allowed memory with unit suffix
	Max string `json:"max"`

	// Min Minimum guaranteed memory with unit suffix
	Min                  string                 `json:"min"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Network Network and port configuration (optional)
type Network struct {
	// Ports Container ports to expose
	Ports                *[]ContainerPort       `json:"ports,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Process Container process configuration (optional)
type Process struct {
	// Args Arguments to the entrypoint.
	// Passed to the command or the container's default entrypoint.
	Args *[]string `json:"args,omitempty"`

	// Command Entrypoint override.
	// Replaces the container image's default entrypoint.
	Command *[]string `json:"command,omitempty"`

	// Env Environment variables
	Env                  *[]EnvVar              `json:"env,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for ContainerPort. Returns the specified
// element and whether it was found
func (a ContainerPort) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerPort
func (a *ContainerPort) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a *ContainerPort) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["containerPort"]; found {
		err = json.Unmarshal(raw, &a.ContainerPort)
		if err != nil {
			return fmt.Errorf("error reading 'containerPort': %w", err)
		}
		delete(object, "containerPort")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a ContainerPort) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["containerPort"], err = json.Marshal(a.ContainerPort)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'containerPort': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerResources. Returns the specified
// element and whether it was found
func (a ContainerResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerResources
func (a *ContainerResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerResources to handle AdditionalProperties
func (a *ContainerResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerResources to handle AdditionalProperties
func (a ContainerResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cpu"], err = json.Marshal(a.Cpu)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
	}

	object["memory"], err = json.Marshal(a.Memory)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContainerSpec. Returns the specified
// element and whether it was found
func (a ContainerSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerSpec
func (a *ContainerSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerSpec to handle AdditionalProperties
func (a *ContainerSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["image"]; found {
		err = json.Unmarshal(raw, &a.Image)
		if err != nil {
			return fmt.Errorf("error reading 'image': %w", err)
		}
		delete(object, "image")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["network"]; found {
		err = json.Unmarshal(raw, &a.Network)
		if err != nil {
			return fmt.Errorf("error reading 'network': %w", err)
		}
		delete(object, "network")
	}

	if raw, found := object["process"]; found {
		err = json.Unmarshal(raw, &a.Process)
		if err != nil {
			return fmt.Errorf("error reading 'process': %w", err)
		}
		delete(object, "process")
	}

	if raw, found := object["providerHints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'providerHints': %w", err)
		}
		delete(object, "providerHints")
	}

	if raw, found := object["resources"]; found {
		err = json.Unmarshal(raw, &a.Resources)
		if err != nil {
			return fmt.Errorf("error reading 'resources': %w", err)
		}
		delete(object, "resources")
	}

	if raw, found := object["serviceType"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'serviceType': %w", err)
		}
		delete(object, "serviceType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerSpec to handle AdditionalProperties
func (a ContainerSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["image"], err = json.Marshal(a.Image)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'image': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Network != nil {
		object["network"], err = json.Marshal(a.Network)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'network': %w", err)
		}
	}

	if a.Process != nil {
		object["process"], err = json.Marshal(a.Process)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'process': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["providerHints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerHints': %w", err)
		}
	}

	object["resources"], err = json.Marshal(a.Resources)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resources': %w", err)
	}

	object["serviceType"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'serviceType': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CpuResources. Returns the specified
// element and whether it was found
func (a CpuResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CpuResources
func (a *CpuResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CpuResources to handle AdditionalProperties
func (a *CpuResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CpuResources to handle AdditionalProperties
func (a CpuResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for EnvVar. Returns the specified
// element and whether it was found
func (a EnvVar) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EnvVar
func (a *EnvVar) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EnvVar to handle AdditionalProperties
func (a *EnvVar) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["value"]; found {
		err = json.Unmarshal(raw, &a.Value)
		if err != nil {
			return fmt.Errorf("error reading 'value': %w", err)
		}
		delete(object, "value")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EnvVar to handle AdditionalProperties
func (a EnvVar) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["value"], err = json.Marshal(a.Value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'value': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Image. Returns the specified
// element and whether it was found
func (a Image) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Image
func (a *Image) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Image to handle AdditionalProperties
func (a *Image) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["reference"]; found {
		err = json.Unmarshal(raw, &a.Reference)
		if err != nil {
			return fmt.Errorf("error reading 'reference': %w", err)
		}
		delete(object, "reference")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Image to handle AdditionalProperties
func (a Image) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["reference"], err = json.Marshal(a.Reference)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'reference': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for MemoryResources. Returns the specified
// element and whether it was found
func (a MemoryResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for MemoryResources
func (a *MemoryResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for MemoryResources to handle AdditionalProperties
func (a *MemoryResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max"]; found {
		err = json.Unmarshal(raw, &a.Max)
		if err != nil {
			return fmt.Errorf("error reading 'max': %w", err)
		}
		delete(object, "max")
	}

	if raw, found := object["min"]; found {
		err = json.Unmarshal(raw, &a.Min)
		if err != nil {
			return fmt.Errorf("error reading 'min': %w", err)
		}
		delete(object, "min")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for MemoryResources to handle AdditionalProperties
func (a MemoryResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["max"], err = json.Marshal(a.Max)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'max': %w", err)
	}

	object["min"], err = json.Marshal(a.Min)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'min': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Network. Returns the specified
// element and whether it was found
func (a Network) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Network
func (a *Network) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a *Network) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ports"]; found {
		err = json.Unmarshal(raw, &a.Ports)
		if err != nil {
			return fmt.Errorf("error reading 'ports': %w", err)
		}
		delete(object, "ports")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Network to handle AdditionalProperties
func (a Network) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Ports != nil {
		object["ports"], err = json.Marshal(a.Ports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ports': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Process. Returns the specified
// element and whether it was found
func (a Process) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Process
func (a *Process) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Process to handle AdditionalProperties
func (a *Process) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["args"]; found {
		err = json.Unmarshal(raw, &a.Args)
		if err != nil {
			return fmt.Errorf("error reading 'args': %w", err)
		}
		delete(object, "args")
	}

	if raw, found := object["command"]; found {
		err = json.Unmarshal(raw, &a.Command)
		if err != nil {
			return fmt.Errorf("error reading 'command': %w", err)
		}
		delete(object, "command")
	}

	if raw, found := object["env"]; found {
		err = json.Unmarshal(raw, &a.Env)
		if err != nil {
			return fmt.Errorf("error reading 'env': %w", err)
		}
		delete(object, "env")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Process to handle AdditionalProperties
func (a Process) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Args != nil {
		object["args"], err = json.Marshal(a.Args)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'args': %w", err)
		}
	}

	if a.Command != nil {
		object["command"], err = json.Marshal(a.Command)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'command': %w", err)
		}
	}

	if a.Env != nil {
		object["env"], err = json.Marshal(a.Env)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'env': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
