// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	. "github.com/dcm-project/catalog-manager/api/v1alpha1"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List catalog items
	// (GET /catalog-items)
	ListCatalogItems(w http.ResponseWriter, r *http.Request, params ListCatalogItemsParams)
	// Create a catalog item
	// (POST /catalog-items)
	CreateCatalogItem(w http.ResponseWriter, r *http.Request, params CreateCatalogItemParams)
	// Delete a catalog item
	// (DELETE /catalog-items/{catalogItemId})
	DeleteCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath)
	// Get a catalog item
	// (GET /catalog-items/{catalogItemId})
	GetCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath)
	// Update a catalog item
	// (PATCH /catalog-items/{catalogItemId})
	UpdateCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List service types
	// (GET /service-types)
	ListServiceTypes(w http.ResponseWriter, r *http.Request, params ListServiceTypesParams)
	// Create a service type
	// (POST /service-types)
	CreateServiceType(w http.ResponseWriter, r *http.Request, params CreateServiceTypeParams)
	// Get a service type
	// (GET /service-types/{serviceTypeId})
	GetServiceType(w http.ResponseWriter, r *http.Request, serviceTypeId ServiceTypeIdPath)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List catalog items
// (GET /catalog-items)
func (_ Unimplemented) ListCatalogItems(w http.ResponseWriter, r *http.Request, params ListCatalogItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a catalog item
// (POST /catalog-items)
func (_ Unimplemented) CreateCatalogItem(w http.ResponseWriter, r *http.Request, params CreateCatalogItemParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a catalog item
// (DELETE /catalog-items/{catalogItemId})
func (_ Unimplemented) DeleteCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a catalog item
// (GET /catalog-items/{catalogItemId})
func (_ Unimplemented) GetCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a catalog item
// (PATCH /catalog-items/{catalogItemId})
func (_ Unimplemented) UpdateCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List service types
// (GET /service-types)
func (_ Unimplemented) ListServiceTypes(w http.ResponseWriter, r *http.Request, params ListServiceTypesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a service type
// (POST /service-types)
func (_ Unimplemented) CreateServiceType(w http.ResponseWriter, r *http.Request, params CreateServiceTypeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a service type
// (GET /service-types/{serviceTypeId})
func (_ Unimplemented) GetServiceType(w http.ResponseWriter, r *http.Request, serviceTypeId ServiceTypeIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCatalogItems operation middleware
func (siw *ServerInterfaceWrapper) ListCatalogItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCatalogItemsParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "service_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_type", r.URL.Query(), &params.ServiceType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "service_type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCatalogItems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) CreateCatalogItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCatalogItemParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCatalogItem(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteCatalogItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "catalogItemId" -------------
	var catalogItemId CatalogItemIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "catalogItemId", chi.URLParam(r, "catalogItemId"), &catalogItemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "catalogItemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCatalogItem(w, r, catalogItemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "catalogItemId" -------------
	var catalogItemId CatalogItemIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "catalogItemId", chi.URLParam(r, "catalogItemId"), &catalogItemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "catalogItemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalogItem(w, r, catalogItemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCatalogItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateCatalogItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "catalogItemId" -------------
	var catalogItemId CatalogItemIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "catalogItemId", chi.URLParam(r, "catalogItemId"), &catalogItemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "catalogItemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCatalogItem(w, r, catalogItemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServiceTypes operation middleware
func (siw *ServerInterfaceWrapper) ListServiceTypes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServiceTypesParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServiceTypes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateServiceType operation middleware
func (siw *ServerInterfaceWrapper) CreateServiceType(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateServiceTypeParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateServiceType(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetServiceType operation middleware
func (siw *ServerInterfaceWrapper) GetServiceType(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceTypeId" -------------
	var serviceTypeId ServiceTypeIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceTypeId", chi.URLParam(r, "serviceTypeId"), &serviceTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceTypeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetServiceType(w, r, serviceTypeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/catalog-items", wrapper.ListCatalogItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/catalog-items", wrapper.CreateCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/catalog-items/{catalogItemId}", wrapper.DeleteCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/catalog-items/{catalogItemId}", wrapper.GetCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/catalog-items/{catalogItemId}", wrapper.UpdateCatalogItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service-types", wrapper.ListServiceTypes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/service-types", wrapper.CreateServiceType)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/service-types/{serviceTypeId}", wrapper.GetServiceType)
	})

	return r
}

type AlreadyExistsJSONResponse Error

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListCatalogItemsRequestObject struct {
	Params ListCatalogItemsParams
}

type ListCatalogItemsResponseObject interface {
	VisitListCatalogItemsResponse(w http.ResponseWriter) error
}

type ListCatalogItems200JSONResponse CatalogItemList

func (response ListCatalogItems200JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItems401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListCatalogItems401JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItems403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListCatalogItems403JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListCatalogItems500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListCatalogItems500JSONResponse) VisitListCatalogItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItemRequestObject struct {
	Params CreateCatalogItemParams
	Body   *CreateCatalogItemJSONRequestBody
}

type CreateCatalogItemResponseObject interface {
	VisitCreateCatalogItemResponse(w http.ResponseWriter) error
}

type CreateCatalogItem201JSONResponse CatalogItem

func (response CreateCatalogItem201JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem400JSONResponse Error

func (response CreateCatalogItem400JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateCatalogItem401JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateCatalogItem403JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem409JSONResponse struct{ AlreadyExistsJSONResponse }

func (response CreateCatalogItem409JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateCatalogItem500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateCatalogItem500JSONResponse) VisitCreateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItemRequestObject struct {
	CatalogItemId CatalogItemIdPath `json:"catalogItemId"`
}

type DeleteCatalogItemResponseObject interface {
	VisitDeleteCatalogItemResponse(w http.ResponseWriter) error
}

type DeleteCatalogItem204Response struct {
}

func (response DeleteCatalogItem204Response) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCatalogItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteCatalogItem401JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItem403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteCatalogItem403JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItem404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCatalogItem404JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCatalogItem500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteCatalogItem500JSONResponse) VisitDeleteCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogItemRequestObject struct {
	CatalogItemId CatalogItemIdPath `json:"catalogItemId"`
}

type GetCatalogItemResponseObject interface {
	VisitGetCatalogItemResponse(w http.ResponseWriter) error
}

type GetCatalogItem200JSONResponse CatalogItem

func (response GetCatalogItem200JSONResponse) VisitGetCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCatalogItem401JSONResponse) VisitGetCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogItem403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetCatalogItem403JSONResponse) VisitGetCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogItem404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCatalogItem404JSONResponse) VisitGetCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogItem500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetCatalogItem500JSONResponse) VisitGetCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItemRequestObject struct {
	CatalogItemId CatalogItemIdPath `json:"catalogItemId"`
	Body          *UpdateCatalogItemApplicationMergePatchPlusJSONRequestBody
}

type UpdateCatalogItemResponseObject interface {
	VisitUpdateCatalogItemResponse(w http.ResponseWriter) error
}

type UpdateCatalogItem200JSONResponse CatalogItem

func (response UpdateCatalogItem200JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItem400JSONResponse Error

func (response UpdateCatalogItem400JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateCatalogItem401JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItem403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateCatalogItem403JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItem404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateCatalogItem404JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateCatalogItem500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateCatalogItem500JSONResponse) VisitUpdateCatalogItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListServiceTypesRequestObject struct {
	Params ListServiceTypesParams
}

type ListServiceTypesResponseObject interface {
	VisitListServiceTypesResponse(w http.ResponseWriter) error
}

type ListServiceTypes200JSONResponse ServiceTypeList

func (response ListServiceTypes200JSONResponse) VisitListServiceTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListServiceTypes400JSONResponse struct{ BadRequestJSONResponse }

func (response ListServiceTypes400JSONResponse) VisitListServiceTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListServiceTypes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListServiceTypes401JSONResponse) VisitListServiceTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListServiceTypes403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListServiceTypes403JSONResponse) VisitListServiceTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListServiceTypes500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListServiceTypes500JSONResponse) VisitListServiceTypesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceTypeRequestObject struct {
	Params CreateServiceTypeParams
	Body   *CreateServiceTypeJSONRequestBody
}

type CreateServiceTypeResponseObject interface {
	VisitCreateServiceTypeResponse(w http.ResponseWriter) error
}

type CreateServiceType201JSONResponse ServiceType

func (response CreateServiceType201JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceType400JSONResponse Error

func (response CreateServiceType400JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateServiceType401JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceType403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateServiceType403JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceType409JSONResponse struct{ AlreadyExistsJSONResponse }

func (response CreateServiceType409JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateServiceType500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateServiceType500JSONResponse) VisitCreateServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetServiceTypeRequestObject struct {
	ServiceTypeId ServiceTypeIdPath `json:"serviceTypeId"`
}

type GetServiceTypeResponseObject interface {
	VisitGetServiceTypeResponse(w http.ResponseWriter) error
}

type GetServiceType200JSONResponse ServiceType

func (response GetServiceType200JSONResponse) VisitGetServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetServiceType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetServiceType401JSONResponse) VisitGetServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetServiceType403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetServiceType403JSONResponse) VisitGetServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetServiceType404JSONResponse struct{ NotFoundJSONResponse }

func (response GetServiceType404JSONResponse) VisitGetServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetServiceType500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetServiceType500JSONResponse) VisitGetServiceTypeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List catalog items
	// (GET /catalog-items)
	ListCatalogItems(ctx context.Context, request ListCatalogItemsRequestObject) (ListCatalogItemsResponseObject, error)
	// Create a catalog item
	// (POST /catalog-items)
	CreateCatalogItem(ctx context.Context, request CreateCatalogItemRequestObject) (CreateCatalogItemResponseObject, error)
	// Delete a catalog item
	// (DELETE /catalog-items/{catalogItemId})
	DeleteCatalogItem(ctx context.Context, request DeleteCatalogItemRequestObject) (DeleteCatalogItemResponseObject, error)
	// Get a catalog item
	// (GET /catalog-items/{catalogItemId})
	GetCatalogItem(ctx context.Context, request GetCatalogItemRequestObject) (GetCatalogItemResponseObject, error)
	// Update a catalog item
	// (PATCH /catalog-items/{catalogItemId})
	UpdateCatalogItem(ctx context.Context, request UpdateCatalogItemRequestObject) (UpdateCatalogItemResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List service types
	// (GET /service-types)
	ListServiceTypes(ctx context.Context, request ListServiceTypesRequestObject) (ListServiceTypesResponseObject, error)
	// Create a service type
	// (POST /service-types)
	CreateServiceType(ctx context.Context, request CreateServiceTypeRequestObject) (CreateServiceTypeResponseObject, error)
	// Get a service type
	// (GET /service-types/{serviceTypeId})
	GetServiceType(ctx context.Context, request GetServiceTypeRequestObject) (GetServiceTypeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCatalogItems operation middleware
func (sh *strictHandler) ListCatalogItems(w http.ResponseWriter, r *http.Request, params ListCatalogItemsParams) {
	var request ListCatalogItemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCatalogItems(ctx, request.(ListCatalogItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCatalogItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCatalogItemsResponseObject); ok {
		if err := validResponse.VisitListCatalogItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCatalogItem operation middleware
func (sh *strictHandler) CreateCatalogItem(w http.ResponseWriter, r *http.Request, params CreateCatalogItemParams) {
	var request CreateCatalogItemRequestObject

	request.Params = params

	var body CreateCatalogItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCatalogItem(ctx, request.(CreateCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCatalogItemResponseObject); ok {
		if err := validResponse.VisitCreateCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCatalogItem operation middleware
func (sh *strictHandler) DeleteCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	var request DeleteCatalogItemRequestObject

	request.CatalogItemId = catalogItemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCatalogItem(ctx, request.(DeleteCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCatalogItemResponseObject); ok {
		if err := validResponse.VisitDeleteCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCatalogItem operation middleware
func (sh *strictHandler) GetCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	var request GetCatalogItemRequestObject

	request.CatalogItemId = catalogItemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCatalogItem(ctx, request.(GetCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCatalogItemResponseObject); ok {
		if err := validResponse.VisitGetCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCatalogItem operation middleware
func (sh *strictHandler) UpdateCatalogItem(w http.ResponseWriter, r *http.Request, catalogItemId CatalogItemIdPath) {
	var request UpdateCatalogItemRequestObject

	request.CatalogItemId = catalogItemId

	var body UpdateCatalogItemApplicationMergePatchPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCatalogItem(ctx, request.(UpdateCatalogItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCatalogItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCatalogItemResponseObject); ok {
		if err := validResponse.VisitUpdateCatalogItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListServiceTypes operation middleware
func (sh *strictHandler) ListServiceTypes(w http.ResponseWriter, r *http.Request, params ListServiceTypesParams) {
	var request ListServiceTypesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListServiceTypes(ctx, request.(ListServiceTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServiceTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListServiceTypesResponseObject); ok {
		if err := validResponse.VisitListServiceTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServiceType operation middleware
func (sh *strictHandler) CreateServiceType(w http.ResponseWriter, r *http.Request, params CreateServiceTypeParams) {
	var request CreateServiceTypeRequestObject

	request.Params = params

	var body CreateServiceTypeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServiceType(ctx, request.(CreateServiceTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServiceType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateServiceTypeResponseObject); ok {
		if err := validResponse.VisitCreateServiceTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServiceType operation middleware
func (sh *strictHandler) GetServiceType(w http.ResponseWriter, r *http.Request, serviceTypeId ServiceTypeIdPath) {
	var request GetServiceTypeRequestObject

	request.ServiceTypeId = serviceTypeId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetServiceType(ctx, request.(GetServiceTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServiceType")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetServiceTypeResponseObject); ok {
		if err := validResponse.VisitGetServiceTypeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
