// Package servicetypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package servicetypes

// Defines values for ServiceType.
const (
	Cluster   ServiceType = "cluster"
	Container ServiceType = "container"
	Database  ServiceType = "database"
	Vm        ServiceType = "vm"
)

// CommonFields Common fields included in all service type specifications.
// These provide versioning, extensibility, and provider-specific configuration.
type CommonFields struct {
	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata ServiceMetadata `json:"metadata"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *ProviderHints `json:"providerHints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType ServiceType `json:"serviceType"`
}

// ProviderHints Optional provider-specific configuration.
//
// Allows platform-specific settings without breaking portability.
// Providers use hints they recognize and ignore unknown hints.
//
// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
// Values are provider-specific configuration objects.
type ProviderHints map[string]map[string]interface{}

// ServiceMetadata Resource metadata for identification and governance.
// Used by all service type specifications.
type ServiceMetadata struct {
	// Labels Key-value pairs for tagging and filtering.
	// Both keys and values must be strings.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier.
	// Must be unique within the namespace.
	Name string `json:"name"`
}

// ServiceType Service type identifier.
// Makes the payload self-describing and enables routing/validation.
type ServiceType string
