// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63LbOJZ+FRRnqmJ3kzJ1ta2tqS3FUjqa8W18yfZ2K+uCyCMRCQmwAdC2kvLffYB9",
	"xH2SLQC8i7LlxElPz+yvKCKIy7l855zvQP5seSyKGQUqhTX8bMWY4wgkcP2/IyxxyJZTCdHUP8cyUF/6",
	"IDxOYkkYtYbWNSW/JYCID1SSBQGOFowjGQDyzMuISIgs24J7HMUhWENLRDgMnVv1JVFTxGpi26I4Uk+9",
	"8pqWbXH4LSEcfGsoeQK2JbwAImz2KiVwNcN//YqdT65z+H4n/eC8/+zag/ZD9v3uv//Zsi25ivX6khO6",
	"tB4ebOsS+C3x4GoVw/MPKMzLSE9bPuCmo4nyat/2aA9qdhEzKkBrchRywP5qck+EUbTHqAQq1UccxyHx",
	"sDrv3gehDv25OIwSh8QktIZlYaE7IgNEfPTqNnKExNTH3H+FsFkFgVlGCUE99NTWXG+wvwwGgbMPhwNn",
	"v++BA93gwIH2cnDQDRa9wwMlKiGxTIQ17LmHtiWJ1AK9AMES7sH6Aum5R8cXk9H4P28mP08vry6th7Is",
	"/8xhYQ2tP+0Vlr5nnoq9CeeMG3FVtZ7KC6UCe7Ct19i/gN8SEPILxfeGQOijV6kR3Kidv0JRIiSiTKI5",
	"IIhiuaoKbf+w2/MXXXB680HX6XUO587cXfSd+YHf7bvgtQd9qAjNLYQ2pbc4JD7iZteo5Nq53Kan70bH",
	"0/HN6OKn65PJ6dULSO419lEmqAfbesP4nPg+0C+U2rUAjnwGQkspwLeAYuAREYIwiiRD2PNACCQDIhBP",
	"7aQqxAPc68Oit3D63n7P6Xex53jtxcDxDqE3aC/8zv5gURFitxDiyMy+yE+Ri+58cnEyvbycnp3ejCen",
	"08n4BWRXCOvBtqZUQQAOldsBN+98mQxHFCUU7mPwJPgI1EyIeV7COfjoLiAhoJgzdVBClxraUpupyrED",
	"B4fkw8EH53DZPnAO92HpLPsfXGfZJQdu/0MwaLsfSnLsV43RHEaDJnCzibIdXk0uTkfHLyDDfCUjN5QO",
	"tK1TJt+whPovgH5V1MutU6NSVWaH8/5gsewvnYF/0HcGvbnv+J3lvuO7i/5+Zwndg/1lxfZ6Dain5l7o",
	"recCOz27unlzdn36ElZ3yiQyknmwrWuKExkwTj7Bl0rqnYYdNY0KmeYF5HHQERSHAmFuLEzFvu1ceOB1",
	"uj50fKeL+x2n1znADh64fQfv+52e68/dfs+viLFdcuHqRvKgm8vy+nR0ffV2cno1PRpdvYgfV4T4kM9X",
	"z6l0pOcsBi6JCdM4Jje3wAUx0q3O+s48QGyhfbQ0ETLzIyIFhAu0A61ly0a3bRzGAW7vtmZ0GkWJxPMQ",
	"EF5I4EodWhytGa2mLuk7ll3OQW5/VZnGjyrleP+j+dyQdNiWnhVuJIlgfftXJAIhcRSjuwDoWoqI7rAw",
	"2wIf7Vy8OULdbvdwt7K7jtsZOG7baXev2r1hxx267i+WbS0Yj7C0hpaPJTh6dZX+YP+MhqssuVrbrE9E",
	"HOLVjUnO1tI+AdxZcALUD1coHYvU2MYEtzWjJ5mAqV9AAgVj4nNAiU4k6wK/VMkwGsMthCyOgEr07sSy",
	"rQjfHwNdqoR00G3YfNyYq+aIoR4jYoRspDPMtuuo7Yq9z5U8+6G2q+rYUsJeMorqmO3S1CeVImLwnnK7",
	"kuFfquEPtpUQ/0tLkxa6Uriz0NkZEYglMk6kw2i4UqqcUbLJddBVAGg6Rh6mSr9Mr4vDcIXUKdSKProl",
	"eEZ/S4CvivwLGTjUk/wbIgttKDFnt8QH385LC+BoCRQ4liAQRtfX03FrRmf0DQtDdifQaHLutDudHDH1",
	"Vhi9VadlVNQNbdB34aDnug6oLLLX9nsO3m8PnF5vMOj3ez3XddvrhhcRmv23bT+/LHlS30nsfx1ihFhI",
	"FDHfiHsL3OgP21+HG9vhMxF1fNgWgtutftXRZjP/x53ZrKX+3VTIFqXkr5UgUoO5Yvepq73PJ2PzD+Cp",
	"7OXewRA7eRwuqlGhJm9GkRv13xviP6gJ4zDhOKyjiFqR0GUSYl57VBwo+zbCFC+Bt3wvahG2VxmsTltC",
	"gGNiCrJqHKVwL29ivIQbyT5Cg66u1NcaDzhITuA2y3zVm0i92ZrRiSrIkJEyItRXKQSkeQoRerg2v3R4",
	"RYuw+uvtL9Evn375+e/k7MP13eLvf/lLU8jkIJLQlOS1CpRzvFK2VDH5TC26uNZi3R4s1XLp+lhNvmY4",
	"2V7sNfmtmUlVCZcpaldPcGlQMM27lKxx5TA28mFBaCb5Mp2COCyAA/VgRlU8NejsMbogy4TjEsBV9a7H",
	"PSbMponSsLDusRPsBdWxZscg1LdCckyoFCbgwwIr2em5zC5mNA3AlYOJslDMEbbSo2YPjsp7UTqICJ2a",
	"t9t13dpWmWlo8IAA0GV5Z2sSKJQgnpNBRk1mXt7L1hluueR6qd19RX5b85aKeDec0M4sssmB8pK+KgT9",
	"NcrYO7TQ4V45iYpt+wfuPjrnbB5ChMa64jI29/bq6hyNzqfCOIxODg67pvpFFxkV2GR+VQ/Kqrj6rt4m",
	"EaaOCo5aynAfh5gan8jmVHmuVlPKLVAPMk3qcl/lyHilXEdiQjOOwclf99PjSIYCCGPkwzwx0ECEWM+c",
	"t+bT1oyxKCy3TRlJIbkqf0I9ta8jkwEmAnzzAsfeR6UyAw3zZLkkdFk/wJbkXp6lJJw4udE3Olla/q7p",
	"TtmGeYg85gPaibD0AhAp15NamhlRyZw0oZhvgFDZ7RQLEyphCZpbSWvttQgQMC5tFFRtRyRRhPmqYhsa",
	"glozehmwJPSVMBXCEiFVRYQ9zkTZrET2rlD1WGWCioS3oUAL8TXj5An2AkKhZPp6OSXHFrpWPjWaaOlq",
	"Nqj0NMvAaRIpuFijWu014sEu0Tp2ndO2GxhH27qYXJ5dXxxNbiY/vx1dX5pZ3oymx5PxzfnF5OjsdDy9",
	"mp6dqvlen12Y52fXVzdnb24uRqc/TfQ2pifnxxO1Kf04J+P0Dt+Npsej18dq4HgyGh9PT9ViR5PJeDJW",
	"sFaS9voJt7XdGrRmkGrsOTOvJgxtCItryWAam9dVOzYP0C0OEyg8XUN2a0Z13PEhBuoLVbPpYlo9eyUy",
	"wmUnrf3MOWxEk2gO3EZzxkLA1EZmpzbSQVkTMQsEPtGh6i8LHAqwK/nkgtyrqlFtqDZYVyOVsYQSSXC4",
	"J5LlEoQsvVd2go5t0SQM1RympNmS+sCeArAQzyGsiQYRiq6ne0fHU7NFFhEpVeXqAye3CgI5i/QONQ2R",
	"slEzXXC0br04aXksoXJmof/97/9BM+udFyfoyHy1W3fho/Nr82wLUiSTVUXpRsi1I/5HADIAjoD6CrW5",
	"0EW8LiNX5ZMay9DVZ4ohSihpyBHm+LkWoSARjBp1PIQsN2zUTqXGTK1mM7/z18uzUyPUdOpcH/V0Scka",
	"JZrP95mOiFnEn5ilxbBJI7maIogYX7UE+QQ3y7l5EIHEPpa4pY1CtCQBPrNq+qpN2YSzGpP1dm4KnhX7",
	"PjH8yXnJeY14GoRwafyvnIYrI82m1iVFrsUdn+OFRB234zrtjjKxM83uGD5bYbrWcMXVVCxK4phxKQpw",
	"Ly/9EVZ3jPtiqCOPjSJCSZRENorwvf4wo2mGaSMVA/QIY756TPYRpKdpnYsMHYcokDIWwz1NsjtGRC3G",
	"l3v6GHvpMcpPnUKkVXXUDehU45OKnsqvPMZBoJ220x7sGvdSG7eG7YGuLNL/2FaUhJLEIZwtynVGOfxX",
	"YbmG5tqWm8D7LeDQmHkVsJuN/whTRomHQ+MBaQZQ6hcURhiYibfhGzelTHoGlEeg+tyrp8sD8+qzCZZ0",
	"72UeJT+O8ucQpNphemOgYFTyQY9zKemw2uWHr+tEVAvcNDJWexDq0xyk+fCP25DIudRnNiPcYffrSMUM",
	"W9cVYcB2M0R+buhsVI75N1g5Jo7FmHCDkx6WsGScfDIVnKFYQgnclCmvmQwUwBluQ79sunZmjTq3/NlK",
	"51tZQ4uCvGP8YyWnLiPDGgp8QSsjNThHzSX2Plfu1TzM6FUpSfJy1GjoA2Tqrhtddf5Ss7dqhdVhL9UB",
	"eZS1OQqxEAWp1uCAqhxlUcRopjdCvTDxYYhuIzsrvlWOqsxtjlXq4oWJkKDq85GvcF+FVMm4QBFepYwX",
	"8hIhVVanjormsGLUV0sL2JL/SRnC7cN8ik4FPVAl4jKYySBXYUqmd0wRi7Eq5H3i6dV4TjuU8jd9mGJ+",
	"w9ToWJzlSGi+qgwezqiD3p0MkUpwbGSSJBsJyThego2WKkM8u7TTjrYafZQJfIhIpAflFK6d3bqwUeo0",
	"6oVxqpYhArokFGyUwnDpTT2xUdqweExV0Yl21EE5C1EcYvW2mhe42FXnugq0CyeeTDigW8yJOiMW4Gf1",
	"Tdn6tPMbOWehYM3xjQjUpzRVtIYHOqxqiWj7JeKjCmwKJGLsEbnSo/pufi1uzlg5TxS+9fBepYlenGiT",
	"4V5AJOg9W0Pr/mBwM+hZtmXyy2GnEVSe2RCsOND/NwT/QA3BSsR+djOwM+z1v08zsGxh22c/bqv9kr3A",
	"GmX9tb3A5jBsGPB6L7AyttoLLD96Mn+tDK5lsd+sF6i0mDbHnt8WPDOhSC+OHOQz496YC0CaKqQGklGE",
	"aaLQ4vFW4uTu5K37ha3EWostjSYpL58x5gaAsvMiTRXrQ2nUekbLqlxfvGTr8UFT+AuWXU/DntL6Wt6r",
	"wHh8dJLdk0InxpDQ6HyagauC0Sy1I5/AR3d4hSRDxuZmtCIv06w0HUMVGcvNKJNVE7rguIivJZoozU3U",
	"0osCrdGO+mJCA0w90Hd/VFLEBA7Fbr4vPfWMZtpyGCdAVVnigyBLqif/05/QRZEbqOzghx9K0hc//DBE",
	"Y5PHSYjiUNur2rFPFpp1kGlixxabDjGjCO28O9mQQf4tmQOnoKZNk0lb23Ypadw12yp1jfW2jlRCB35u",
	"mkxtSNUY5op5NTurNW7VnrQmChZIW2dIPKBCw1WaYoxi7AWAOi3Xsq2E66I6JVnu7u5aWD/WHEv6rtg7",
	"nh5NTi8nTqfltgIZhaU2h7XBrEqQWipcH2yLxUBxTKyh1W25rZ6B9EA70F71ksTws7UE2VQOaWTSFhvj",
	"JaFaaCERsn5FQJSZq7yoq2eyxo0VTGpRTn1raCn4LKtHb7P4OcivX4Wb2S8iNIgUP4koOXr51uVaUFvv",
	"ymiuKiXctd1qN5QKuGTCKYqB6z1sWDjC9wZlVN5aWTtnjtuNza+CJXPV8zJPVifG1rf9RuujBh3rqtH0",
	"pDmHSAfdBcANrduq5OhFJ4+IRoa59GuUmgjqDeyN0n9f+zFJx3W3uBq83R3a+lWehtu0l4muphZJmPcq",
	"lVP13PamyfPd7lVv4qqXuk+/VLmG3zeHffyNprv6+t6vaXWmzlXVu+Y+mGhw9iNNPClXp3BXv5RS8u5E",
	"AHeK0mI6Fqq80C74ivivUL3M0DHKhyhmEqi3asIAs3T50tATIHCWFjn1zVSuakzHj/4ArGaXxLce+S3U",
	"M38I9d7kGSDka+avvoXZZr+2Kv+W62HNY9rfbuk6TV4SfEZhityFwpVxg5fz4Ed+iVHtvs+Zv0LZ9Shk",
	"IuD38+Oee/j0G9Wfyb2c9xu3qt1/02P2Hr2WbbAhBAlN3esQDErUEGLNqc3IR5266YDFkL31H4I2BIVe",
	"U8+mZIzmIE3G+J0MoPf0G/mPhF5O90b6a7q3n070TLunCqXzFSJSIE39rCn6J5DfXMvu7wJki0wp/+TG",
	"8hPIBkuJVZLXwGdqrkzUiiRdxVXnSG8C6Pb1CfAloHNd1WuGbL97ONjVicUpk4BkgCUq0UaGBa7nnfb6",
	"V8ULHB4hSRvM1pzjW1juNoE/UgJxtIh//MZJwO/jO4ZS/Z2TALOJ/Iel//yebIy6MeQH+b2HxhCQ3j3w",
	"AvA+6px9M92wBv9vi5sP38jy3mYXCB42dOwQESi7JFEVSflgRhJVVvjLyI9NJF3jDZ70dQVTBhM1TaEJ",
	"CLGJEykzaS/KiahKf67JtNKduRr/mWbLGtJjDreEJSIvg1My9nfhVczlN8pk0dyyi59BSIbarrt5f9+F",
	"fvmWyUu97fAc3mILfCn9tYk/JtVR9sqtqY4NrvzSrMfU3JqYjhVUbey13pEwzBuuiFHYzJeUOx1fyJdM",
	"x83N6Bk9SYRMuwZofHrptNudbnEvN8IS7YTsDriHBSDNOdMkAk48w6AHqzgAKnZrd3Wbm8o0Lyy24A//",
	"CDxNpQf1fXmataWbo6W29X9Inqa4VJr+uY5/NbKm8gee1vOV+sWzrfKXtKavIN1TNf2j8PJEZbT+F66+",
	"V1h80uj/tWr6mjGlN/0yLZqe5B6OyV7ROHz/8H8BAAD//0wwHomfTQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
