// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"time"
)

// Defines values for ErrorType.
const (
	ABORTED            ErrorType = "ABORTED"
	ALREADYEXISTS      ErrorType = "ALREADY_EXISTS"
	DEADLINEEXCEEDED   ErrorType = "DEADLINE_EXCEEDED"
	FAILEDPRECONDITION ErrorType = "FAILED_PRECONDITION"
	INTERNAL           ErrorType = "INTERNAL"
	INVALIDARGUMENT    ErrorType = "INVALID_ARGUMENT"
	NOTFOUND           ErrorType = "NOT_FOUND"
	OUTOFRANGE         ErrorType = "OUT_OF_RANGE"
	PERMISSIONDENIED   ErrorType = "PERMISSION_DENIED"
	RESOURCEEXHAUSTED  ErrorType = "RESOURCE_EXHAUSTED"
	UNAUTHENTICATED    ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE        ErrorType = "UNAVAILABLE"
	UNIMPLEMENTED      ErrorType = "UNIMPLEMENTED"
)

// CatalogItem defines model for CatalogItem.
type CatalogItem struct {
	// ApiVersion Version of the CatalogItem schema itself (e.g., v1alpha1).
	// Immutable after creation.
	ApiVersion string `json:"api_version"`

	// CreateTime Timestamp when the catalog item was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// DisplayName User-friendly display name for the catalog item.
	// Mutable and does not need to be unique.
	DisplayName string `json:"display_name"`

	// Path Resource path in the format: catalog-items/{catalogItemId}
	Path *string `json:"path,omitempty"`

	// Spec Specification for a catalog item, defining the service type reference
	// and field configurations.
	Spec CatalogItemSpec `json:"spec"`

	// Uid Unique identifier for the catalog item. This field is output-only and
	// immutable after creation. The ID can be optionally specified via
	// query parameter on creation; if not provided, the server generates a UUID.
	//
	// Follows AEP-122 resource ID conventions.
	Uid *string `json:"uid,omitempty"`

	// UpdateTime Timestamp when the catalog item was last modified (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version Version of this catalog item.
	// Immutable after creation.
	Version string `json:"version"`
}

// CatalogItemList defines model for CatalogItemList.
type CatalogItemList struct {
	// NextPageToken Token for retrieving the next page.
	// Empty string indicates this is the last page.
	NextPageToken string `json:"next_page_token"`

	// Results Array of catalog item resources
	Results []CatalogItem `json:"results"`
}

// CatalogItemSpec Specification for a catalog item, defining the service type reference
// and field configurations.
type CatalogItemSpec struct {
	// Fields Array of field configurations for this catalog item.
	// Each configuration defines constraints and defaults for fields
	// in the service type specification.
	Fields []FieldConfiguration `json:"fields"`

	// ServiceType The Service type this catalog item references.
	// Immutable after creation.
	ServiceType string `json:"service_type"`

	// ServiceTypeVersion Version of the ServiceType this catalog item references.
	// Immutable after creation.
	ServiceTypeVersion string `json:"service_type_version"`
}

// Error Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Error struct {
	// Detail Human-readable explanation specific to this occurrence of the error.
	// May contain request-specific details to help debug the issue.
	Detail *string `json:"detail,omitempty"`

	// Instance Unique identifier for this specific error occurrence.
	// Can be used for tracking and debugging.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code (matches the response status)
	Status int32 `json:"status"`

	// Title Short, human-readable summary of the error type.
	// Should be consistent across occurrences of the same error type.
	Title string `json:"title"`

	// Type Machine-readable error code. Uses AEP standard error codes.
	Type ErrorType `json:"type"`
}

// ErrorType Machine-readable error code. Uses AEP standard error codes.
type ErrorType string

// FieldConfiguration defines model for FieldConfiguration.
type FieldConfiguration struct {
	// Default Default value for this field.
	// Type depends on the field's schema (can be string, number, boolean, object, array).
	// If editable=false, this is the fixed value.
	// If editable=true, this is the initial/suggested value.
	Default interface{} `json:"default"`

	// DisplayName User-facing label for this field in UI/CLI.
	// If omitted, derived from the path (e.g., "spec.vcpu.count" → "Vcpu Count").
	DisplayName *string `json:"display_name,omitempty"`

	// Editable Whether end users can modify this field value when requesting services.
	// If false, the field is fixed to the default value.
	Editable *bool `json:"editable,omitempty"`

	// Path JSON path to the field in the ServiceType spec using dot notation.
	// Examples: "spec.vcpu.count", "spec.memory.size_gb", "metadata.labels.tier"
	Path string `json:"path"`

	// ValidationSchema JSON Schema constraints for validating this field (draft 2020-12).
	// Only applicable when editable=true.
	// Supports standard JSON Schema keywords: type, minimum, maximum,
	// pattern, enum, minLength, maxLength, etc.
	//
	// Reference: https://json-schema.org/draft/2020-12/json-schema-validation
	ValidationSchema *map[string]interface{} `json:"validation_schema,omitempty"`
}

// Health defines model for Health.
type Health struct {
	// Path Canonical path of the resource
	Path *string `json:"path,omitempty"`

	// Status Health status
	Status string `json:"status"`
}

// ServiceType defines model for ServiceType.
type ServiceType struct {
	// ApiVersion Version of the service type schema (e.g., v1alpha1, v1beta1, v1).
	// Immutable after creation.
	ApiVersion string `json:"api_version"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`
	Metadata   *struct {
		// Labels Key-value pairs for categorization and filtering.
		// Both keys and values are strings.
		Labels *map[string]string `json:"labels,omitempty"`
	} `json:"metadata,omitempty"`

	// Path Resource path in the format: service-types/{serviceTypeId}
	// This is the canonical identifier for the resource.
	Path *string `json:"path,omitempty"`

	// ServiceType Classification of the service type.
	// Common values include: vm, container, database, cluster.
	// Administrators may define custom types beyond these.
	ServiceType string `json:"service_type"`

	// Spec Service-specific configuration schema (required).
	// This is an opaque dictionary containing service type-specific fields.
	//
	// Examples by service type:
	// - VM: vcpu, memory, storage, guestOS, access
	// - Container: image, resources, process, network
	// - Database: engine, version, resources
	// - Cluster: version, nodes (control plane, workers)
	//
	// The structure varies based on the service_type and schema_version.
	Spec map[string]interface{} `json:"spec"`

	// Uid Unique identifier for the service type. This field is output-only and
	// immutable after creation. The ID can be optionally specified via
	// query parameter on creation; if not provided, the server generates a UUID.
	//
	// Follows AEP-122 resource ID conventions.
	Uid *string `json:"uid,omitempty"`

	// UpdateTime Timestamp when the resource was last modified (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version Version of this service type
	// Immutable after creation.
	Version string `json:"version"`
}

// ServiceTypeList defines model for ServiceTypeList.
type ServiceTypeList struct {
	// NextPageToken Token for retrieving the next page of results.
	// Empty string indicates this is the last page.
	// Opaque token - do not parse or construct manually.
	NextPageToken string `json:"next_page_token"`

	// Results Array of service type resources.
	// May be empty if no results match the query.
	Results []ServiceType `json:"results"`
}

// CatalogItemIdPath defines model for CatalogItemIdPath.
type CatalogItemIdPath = string

// ServiceTypeIdPath defines model for ServiceTypeIdPath.
type ServiceTypeIdPath = string

// AlreadyExists Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type AlreadyExists = Error

// BadRequest Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type BadRequest = Error

// Forbidden Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Forbidden = Error

// InternalServerError Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type InternalServerError = Error

// NotFound Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type NotFound = Error

// Unauthorized Error response following RFC 7807 Problem Details for HTTP APIs
// and AEP-193 Error Responses specification.
type Unauthorized = Error

// ListCatalogItemsParams defines parameters for ListCatalogItems.
type ListCatalogItemsParams struct {
	// PageToken Token for retrieving the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of items to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// ServiceType Filter catalog items by service type.
	// Only returns items where spec.service_type matches this value.
	ServiceType *string `form:"service_type,omitempty" json:"service_type,omitempty"`
}

// CreateCatalogItemParams defines parameters for CreateCatalogItem.
type CreateCatalogItemParams struct {
	// Id Optional user-specified catalog item ID
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// ListServiceTypesParams defines parameters for ListServiceTypes.
type ListServiceTypesParams struct {
	// PageToken Token for retrieving the next page of results.
	// Obtained from the next_page_token field of a previous response.
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of items to return per page.
	// If not specified, defaults to 100.
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateServiceTypeParams defines parameters for CreateServiceType.
type CreateServiceTypeParams struct {
	// Id Optional user-specified ID for the service type.
	// Must follow DNS-1123 label format (lowercase alphanumeric with hyphens).
	// If omitted, the server generates an ID.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateCatalogItemJSONRequestBody defines body for CreateCatalogItem for application/json ContentType.
type CreateCatalogItemJSONRequestBody = CatalogItem

// UpdateCatalogItemApplicationMergePatchPlusJSONRequestBody defines body for UpdateCatalogItem for application/merge-patch+json ContentType.
type UpdateCatalogItemApplicationMergePatchPlusJSONRequestBody = CatalogItem

// CreateServiceTypeJSONRequestBody defines body for CreateServiceType for application/json ContentType.
type CreateServiceTypeJSONRequestBody = ServiceType
